yarnPath: .yarn/releases/yarn-4.6.0.cjs
nodeLinker: pnp

packageExtensions:
  "@fastify/autoload@*":
    peerDependencies:
      fastify: "^5"
  "fastify-plugin@*":
    peerDependencies:
      fastify: "^5"
  "@fastify/cors@*":
    peerDependencies:
      fastify: "^5"
  "fastify-graceful-shutdown@*":
    peerDependencies:
      fastify: "^5"
  "@fastify/env@*":
    peerDependencies:
      fastify: "^5"
